baseURL: https://slovakdiaspora.com/
languageCode: en-us
title: Slovak Diaspora
theme: cleanwhite
enableRobotsTXT: true

params:
  header_image: images/martin-katler-unsplash.jpg
  description: foobar

  addtional_menus:
  - title: CITIZENSHIP
    href: /citizenship/
  #- title: RESOURCES
  #  href: /resources/
  #- title: EVENTS
  #  href: /events/